version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
